Repository beam-community/elixir-companies, pull requests merged in 2019-03, with the labels that each got.

#467 Fix required Github permissions during authorization, #461
  config/config.exs
Labels: enhancement

#468 Add AppSignal integration
  config/config.exs
  lib/companies/application.ex
  lib/companies_web/endpoint.ex
  mix.exs
  mix.lock
Labels: enhancement

#470 Ensure distinct companies. Minimize sub queries
  lib/companies/companies.ex
Labels: bug

#477 Correct issue with distinct/3
  lib/companies/companies.ex
Labels: bug

#478 Travis should run our tests
  .travis.yml
  README.md
Labels: enhancement

#484 Rotate hiring ribbon element
  assets/css/app.scss
  assets/css/libs/_ribbon.sass
  lib/companies_web/templates/company/card.html.eex
Labels: enhancement

#490 Update schema tests to be consistent
  test/companies/schema/company_test.exs
  test/companies/schema/industry_test.exs
  test/companies/schema/job_test.exs
  test/companies/schema/pending_changes_test.exs
  test/companies/schema/user_test.exs
Labels: enhancement

#491 Add 404 error page
  assets/css/app.scss
  assets/css/errors.scss
  lib/companies_web/templates/error/404_page.html.eex
  lib/companies_web/views/error_view.ex
Labels: enhancement

#492 Improve typography
  assets/css/app.scss
  lib/companies_web/templates/company/recent.html.eex
  lib/companies_web/templates/layout/footer.html.eex
Labels: discussion, enhancement

#489 feat: update edit and delete buttons for company cards, #469
  assets/css/app.scss
  assets/css/libs/_ribbon.sass
  assets/js/app.js
  lib/companies_web/templates/company/card.html.eex
  lib/companies_web/templates/company/index.html.eex
  lib/companies_web/templates/company/recent.html.eex
Labels: enhancement

#495 Add support gettext
  config/config.exs
  lib/companies_web/helpers/site_helpers.ex
  lib/companies_web/templates/company/card.html.eex
  lib/companies_web/templates/company/edit.html.eex
  lib/companies_web/templates/company/form.html.eex
  lib/companies_web/templates/company/hiring.html.eex
  lib/companies_web/templates/company/index.html.eex
  lib/companies_web/templates/company/new.html.eex
  lib/companies_web/templates/company/recent.html.eex
  lib/companies_web/templates/company/show.html.eex
  lib/companies_web/templates/error/404_page.html.eex
  lib/companies_web/templates/job/edit.html.eex
  lib/companies_web/templates/job/form.html.eex
  lib/companies_web/templates/job/new.html.eex
  lib/companies_web/templates/job/show.html.eex
  lib/companies_web/templates/layout/account.html.eex
  lib/companies_web/templates/layout/footer.html.eex
  lib/companies_web/templates/layout/navbar.html.eex
  priv/gettext/default.pot
  priv/gettext/en/LC_MESSAGES/default.po
  priv/gettext/errors.pot
Labels: discussion, enhancement

#503 Separate authenticate and authorize plugs
  lib/companies_web/plugs/authorize.ex
  lib/companies_web/router.ex
  test/companies_web/plugs/authorize_test.exs
  test/test_helper.exs
Labels: bug

#507 Move distinct/2 into individual predicate functions
  lib/companies/companies.ex
  test/companies/companies_test.exs
Labels: bug
