Repository beam-community/elixir-companies, pull requests merged in 2019-10, with the labels that each got.

#534 Adds Filters for Companies / Jobs - Seperates Jobs into new route
  config/config.exs
  lib/companies.ex
  lib/companies/companies.ex
  lib/companies/industries.ex
  lib/companies/jobs.ex
  lib/companies/repo.ex
  lib/companies_web/controllers/company_controller.ex
  lib/companies_web/controllers/job_controller.ex
  lib/companies_web/router.ex
  lib/companies_web/templates/company/index.html.eex
  lib/companies_web/templates/job/index.html.eex
  lib/companies_web/templates/job/job.html.eex
  lib/companies_web/templates/layout/navbar.html.eex
  lib/companies_web/views/company_view.ex
  lib/companies_web/views/job_view.ex
  test/companies/companies_test.exs
  test/companies/jobs_test.exs
Labels: Hacktoberfest, enhancement

#538 Bump Appsignal dependency
  mix.lock
Labels: Hacktoberfest

#537 Markdown format for company description
  lib/companies_web/templates/company/card.html.eex
  lib/companies_web/templates/company/form.html.eex
  lib/companies_web/templates/layout/app.html.eex
  lib/companies_web/views/company_view.ex
  mix.exs
  mix.lock
  test/companies_web/views/company_view_test.exs
Labels: Hacktoberfest, enhancement

#543 Fix mobile view and accessibility
  assets/css/app.scss
  lib/companies_web/templates/company/index.html.eex
  lib/companies_web/templates/job/index.html.eex
  lib/companies_web/templates/layout/footer.html.eex
  lib/companies_web/templates/layout/navbar.html.eex
Labels: enhancement
